package com.threatweave.threatweave;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/** 创建 ThreatWeave 业务所需的数据库结构。 */
@Component
public class ThreatWeaveSchemaInitializer implements ApplicationRunner {
    private final JdbcTemplate jdbcTemplate;

    public ThreatWeaveSchemaInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS threatweave");
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS threatweave.documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                doc_key TEXT NOT NULL UNIQUE, source_id TEXT NOT NULL, source_name TEXT NOT NULL, external_id TEXT,
                title TEXT, url TEXT, published_at TIMESTAMPTZ, content TEXT NOT NULL,
                content_sha256 TEXT NOT NULL, formatted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                ingested_at TIMESTAMPTZ NOT NULL DEFAULT now(), created_at TIMESTAMPTZ NOT NULL DEFAULT now()
            )""");
        // 兼容已由旧版本创建的 documents 表；新写入路径始终提供稳定 source_id。
        jdbcTemplate.execute("ALTER TABLE threatweave.documents ADD COLUMN IF NOT EXISTS source_id TEXT");
        jdbcTemplate.execute("UPDATE threatweave.documents SET source_id = source_name WHERE source_id IS NULL");
        jdbcTemplate.execute("ALTER TABLE threatweave.documents ALTER COLUMN source_id SET NOT NULL");
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS threatweave.entities (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entity_type TEXT NOT NULL CHECK (entity_type IN ('ipv4', 'ipv6', 'domain', 'url', 'file_hash', 'cve', 'threat_actor', 'malware', 'campaign', 'attack_technique', 'tool', 'organization')),
                canonical_value TEXT NOT NULL, display_name TEXT,
                semantic_role TEXT NOT NULL DEFAULT 'unknown' CHECK (semantic_role IN ('malicious_infrastructure', 'victim', 'research', 'unknown')), confidence SMALLINT CHECK (confidence BETWEEN 0 AND 100),
                first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ, revoked BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (entity_type, canonical_value)
            )""");
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS threatweave.entity_aliases (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entity_id BIGINT NOT NULL REFERENCES threatweave.entities(id) ON DELETE CASCADE,
                alias TEXT NOT NULL, source_url TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                UNIQUE (entity_id, alias)
            )""");
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS threatweave.relations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                src_entity_id BIGINT NOT NULL REFERENCES threatweave.entities(id) ON DELETE CASCADE,
                dst_entity_id BIGINT NOT NULL REFERENCES threatweave.entities(id) ON DELETE CASCADE,
                relation_type TEXT NOT NULL CHECK (relation_type IN ('USES', 'ATTRIBUTED_TO', 'INDICATES', 'RESOLVES_TO', 'TARGETS', 'EXPLOITS', 'COMMUNICATES_WITH')),
                confidence SMALLINT CHECK (confidence BETWEEN 0 AND 100), first_seen_at TIMESTAMPTZ,
                last_seen_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CHECK (src_entity_id <> dst_entity_id), UNIQUE (src_entity_id, dst_entity_id, relation_type)
            )""");
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS threatweave.provenance (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                document_id BIGINT NOT NULL REFERENCES threatweave.documents(id) ON DELETE CASCADE,
                entity_id BIGINT REFERENCES threatweave.entities(id) ON DELETE CASCADE,
                relation_id BIGINT REFERENCES threatweave.relations(id) ON DELETE CASCADE,
                evidence_quote TEXT NOT NULL, char_start INTEGER NOT NULL CHECK (char_start >= 0),
                char_end INTEGER NOT NULL CHECK (char_end > char_start), extractor TEXT NOT NULL,
                confidence SMALLINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CHECK ((entity_id IS NOT NULL) <> (relation_id IS NOT NULL)),
                UNIQUE NULLS NOT DISTINCT (document_id, entity_id, relation_id, evidence_quote, char_start, char_end, extractor)
            )""");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS documents_source_published_idx ON threatweave.documents (source_name, published_at DESC)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS entities_type_value_idx ON threatweave.entities (entity_type, canonical_value)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS entity_aliases_alias_idx ON threatweave.entity_aliases (alias)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS relations_src_idx ON threatweave.relations (src_entity_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS relations_dst_idx ON threatweave.relations (dst_entity_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS relations_type_idx ON threatweave.relations (relation_type)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS provenance_document_idx ON threatweave.provenance (document_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS provenance_entity_idx ON threatweave.provenance (entity_id)");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS provenance_relation_idx ON threatweave.provenance (relation_id)");
    }
}
